### ISSUE TITLE
multiple thesorus criteria

### ISSUE THREAD

**Issue by simonLouvet** [AdvancedCartographyWebComponent/ACWC-Tree#1]
lorsque on sélectionne plusieurs critères dans le thésaurus, toutes les données sont affichées dans la carte et non celle filtrées

![image](https://cloud.githubusercontent.com/assets/5068825/26257300/67147b00-3cc0-11e7-8113-ba1b82a202fb.png)

**Comment by simonLouvet** [comment]
remplacer les bouton (on/off) par des cases à cocher)

**Comment by simonLouvet** [comment]
afficher le label des thesorus et non une donnée technique

**Comment by yuchaoqian** [comment]
solved
